### ISSUE TITLE
several koubachi devices config.yaml

### ISSUE THREAD

**Issue by polpas** [munzli/koubachi-goserver#4]
May you please give me an example of how to define several koubachi devices?

**Comment by munzli** [comment]
as yaml dictionary
```
output:
  db_file: "./readings/koubachi.db"
devices:
  0006666a6666:
    name: "pilsner"
    key: 1239d1742290fd8f1715f277432bd456
    calibration_parameters:
      SOIL_MOISTURE_DISCONTINUITY: 9761.57
      SOIL_MOISTURE_MIN: 3356.0
  0006666a7777:
    name: "amber"
    key: 123ecd0e6a8f1e3893e7aa7fb39de456
    calibration_parameters:
      LM94022_TEMPERATURE_OFFSET: -4.93952902424635
      LM94022_VOLTAGE: 0.935589
      REFERENCE_TEMPERATURE: 23.045
      RN171_SMU_DC_OFFSET: 0.00024
      RN171_SMU_GAIN: 1.05362973229787
      RN171_SMU_REFERENCE_VOLTAGE_EXTERNAL: 0.294951
      RN171_SMU_REFERENCE_VOLTAGE_INTERNAL: 0.280178
      SFH3710_DC_OFFSET_CORRECTION: 1.3e-05
      SOIL_MOISTURE_DISCONTINUITY: 9139.13
      SOIL_MOISTURE_MIN: 3322.0
  0006666a8888:
    name: "stout"
    key: 123ab54e30f184fc4e7e95952936e456
    calibration_parameters:
      SOIL_MOISTURE_DISCONTINUITY: 9031.0
      SOIL_MOISTURE_MIN: 3562.0
```
